### PR TITLE
WIP: Linux support

### PR DESCRIPTION
**Pull request by fnr1r**
This PR adds Linux support.

Here's what currently works:

- Launching the game
- Launching the GC server
- Registry wiping
- Builtin proxy
- Downloading things
- Service control
- Installing CA certs (on Debian and Arch-based distros)
- 3dmigoto

Here's what I'm unsure about:

- Akebi/Acrepi
- Reshade Injector
- Anything not on the previous list

### CODE REVIEW

**Comment by fnr1r** [comment]
Rebased on `main`, updated `anime-launcher-sdk`, squashed "Fix build on Windows" 8ff6397 into the commit that introduced that issue and complied with clippy.

**Comment by SpikeHD** [comment]
What sorts of uncertainties do you have regarding reshade and Akebi/Acrepi/etc.? Are you unable to test them, or do you know they don't work?

**Comment by fnr1r** [comment]
I'm not sure if they work.
I don't have a copy of Akebi with which I could test the game with.
As for reshade, I haven't got around to it yet.

**Comment by SpikeHD** [comment]
Okay, that's fine. I would feel fine merging without knowing if they work or not, I'll give a full code review when I have some free time :+1:

**Comment by fnr1r** [comment]
Reshade does not work. Video: https://youtu.be/hYzUbkH8R14
Should I still add the code necessary for running the injector from the launcher?

**Comment by SpikeHD** [comment]
I think it should be kept, no way to know if a new Wine version would just fix it or whatever. I would imagine it to be a similar situation with Akebi-likes, so we can just assume they would work the same.

**Comment by fnr1r** [comment]
Moved terminal detection to `term-detect`, updated `anime-launcher-sdk` and complied with clippy (I missed one commit last time).

**Comment by fnr1r** [comment]
Oops. I was cleaning up branches and did not expect renaming the `linux` branch to close the PR.
Since <https://github.com/MrLGamer/GIMI-for-Linux> was updated, I'll reopen the pull request with the part2 branch, which does not contain support for 3dmigoto.

**Pull request closed without merging**
