### PR TITLE
Refactor cultivation to use solid-js and add a bunch of QoL changes

### PR DESCRIPTION
**Pull request by Drevoed**
# WIP!!!

This PR is mainly a mashup of all the things I could find that could have an improve. I will write a detailed list later.

For now here are the core changes:

- Move to `solid-js`
- Precise tracking of tauri IPC
- TS stricter typing via module augmentation
- Declarative UI description
- Scalable architecture with enforced API layers
- Utilize `tokio` thread pool to the max by not using blocking std apis inside of async fns
- Support chain cancellation where it's needed
- Use `vite`/`vitest` tooling to improve DX
- A bunch of `prettier` and `eslint` configs changes
- Avoid using lazy std mutexes in favour of lockfree, concurrent data structures (e.g - `dashmap`)
- Proper error handling in rust via `thiserror` and `serde`. No more unwraps!
- Different performance optimizations both on backend and frontend (e.g - share reqwest client between commands; batch reactive updates inside listeners)
- Soft deprecation of global theming via css files, currently work is not yet started on defining a correct theme entrypoint.
- Use vanilla-extract to ensure css is atomic and easy to work with

Not yet implemented but kept in mind:

- Logging by levels (both fe and be)
- More improvements to the IPC and scrutinize security 
- Move more work to the backend
- Cache for computation/network heavy workloads and its invalidation
- Theme browser and switcher
- UA patching (not sure if even possible. but if someone has a guide on how to do it manually - then sure.)

This should obviously be 2.0 release, if it will ever be merged.

### CODE REVIEW

**Comment by nitrog0d** [comment]
kanye east

**Comment by SpikeHD** [comment]
This is... SO many changes man. I have to ask that you split this up because this is wayyyyyy too much to review at once.

**Comment by Drevoed** [comment]
Yeah, sure, I'll cherry pick the features one by one into separate branches, so merging would be easier

**Comment by Drevoed** [comment]
Maybe also makes sense to create a `next` or `dev` as a main branch for that?

cc @SpikeHD

**Comment by Drevoed** [comment]
The thing is, changing architecture pr by pr will be relatively slow and painful, but I can make it work, yeah

**Comment by SpikeHD** [comment]
Sure, I'll make a new branch ("dev") you can target in future PRs

**Pull request closed without merging**
