### PR TITLE
Fix build errors on Unix

### PR DESCRIPTION
**Pull request by Seeker14491**
This gets the launcher building and running on Linux (and Mac, though I haven't tested it). There are still some more things to fix, not including implementing the actual proxying which I won't implement in this PR.

### CODE REVIEW

**Comment by Seeker14491** [comment]
@RBNXI I'm guessing you're missing the Tauri development prerequisites: https://tauri.app/v1/guides/getting-started/prerequisites

**Comment by SpikeHD** [comment]
@RBNXI Try installing `yarn` and running `yarn start:dev`. You can also just run the command manually, which can be found in `package.json`

**Comment by SpikeHD** [comment]
@RBNXI Ty for letting me know I'll just pop that in rq instead

**Comment by Seeker14491** [comment]
I might not have time to fix everything I intended, so I think we should merge this for now. Also we'll probably have to change a lot of the path handling code on the backend first, as right now it mostly works with `String`/`str` instead of `PathBuf`/`Path`, and that will break things.

**Comment by SpikeHD** [comment]
Fair enough, appreciate the work, I will make a point of converting what I can to PathBuf at some point

**Pull request merged**
